CONNECT sys/system2@sssbda_s2 AS SYSDBA;

CREATE USER santiago10 IDENTIFIED BY 1234 QUOTA UNLIMITED ON users;

GRANT CREATE TABLE, CREATE SESSION, CREATE PROCEDURE TO santiago10;

CONNECT sys/system2 AS SYSDBA;

ALTER SYSTEM SET processes = 200 SCOPE = spfile;

SHUTDOWN IMMEDIATE;

STARTUP OPEN;